// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroMoraBlazor.DAL;

namespace RegistroMoraBlazor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200618133732_CreateMoraDB")]
    partial class CreateMoraDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("RegistroMoraBlazor.Models.Mora", b =>
                {
                    b.Property<int>("moraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("total")
                        .HasColumnType("TEXT");

                    b.HasKey("moraId");

                    b.ToTable("Moras");
                });

            modelBuilder.Entity("RegistroMoraBlazor.Models.MoraDetalle", b =>
                {
                    b.Property<int>("moraDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("moraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("prestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valor")
                        .HasColumnType("TEXT");

                    b.HasKey("moraDetalleId");

                    b.HasIndex("moraId");

                    b.ToTable("MoraDetalle");
                });

            modelBuilder.Entity("RegistroMoraBlazor.Models.Personas", b =>
                {
                    b.Property<int>("personaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.HasKey("personaId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RegistroMoraBlazor.Models.Prestamo", b =>
                {
                    b.Property<int>("prestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("personaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("prestamoId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("RegistroMoraBlazor.Models.MoraDetalle", b =>
                {
                    b.HasOne("RegistroMoraBlazor.Models.Mora", null)
                        .WithMany("MoraDetalles")
                        .HasForeignKey("moraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
